dataset:
  path_to_dataset: 'data/dataset/hyperparameter_tuning'
  n_sets: 3
  prefix: 'set_'

run:
  save_path: 'results/hyperparameter_tuning'
  n_trials: 50

training_params:
  train_size: 193
  validation_size: 20
  epochs: 50
  learning_rate: 0.0001

common:
  sequence_size: [60, 420, 10]
  fc_layers: [1, 5, 1]
  fc_neurons: [16, 128, 8]
  dropout: [0.1, 0.5, 0.1]

cnn:
  conv_layers: [1, 3, 1]
  channels: [16, 128, 8]
  kernel_size: [3, 7, 2]
  stride_size: [1, 2, 1]

lstm:
  hidden_size: [16, 128, 8]
  lstm_size: [1, 5, 1]

transformer:
  embedding_size: [16, 64, 8]
  num_heads: [2, 4, 2]
  dim_feedforward: [32, 256, 16]
  num_layers: [1, 3, 1]

